name: Build

on:
  push:
    branches:
      - develop

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  pull_request:

env:
  CONTAINER_REGISTRY: ghcr.io

jobs:
  image:
    name: Image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ["3.12"]
        alpine_version: ["3.19"]
        pyinstaller_tag: ["v6.5.0"]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ github.repository_owner }}
          # For GITHUB_TOKEN to work, you have to give Write permission to the
          # repository for the Container Image in GitHub Packages.
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: "alpine${{ matrix.alpine_version }}-python${{ matrix.python_version }}-pyinstaller${{ matrix.pyinstaller_tag }}"
          platforms: linux/arm/v7,linux/arm64/v8,linux/amd64
          build-args: |
            SOURCE_COMMIT=${{ env.GITHUB_SHA }}
            SOURCE_REF=${{ env.GITHUB_HEAD_REF }}
            PYINSTALLER_TAG=${{ matrix.pyinstaller_tag }}
            PYTHON_VERSION=${{ matrix.python_version }}
            ALPINE_VERSION=${{ matrix.alpine_version }}

#      - name: Push container image
#        if: ${{ github.event_name != 'pull_request' && !env.ACT}}
#        run: |
